### PR TITLE
Fixed function overloading and combining Options with locals.

### PR DESCRIPTION
**Pull request by MichalLytek**
Fixed PR #3.

### CODE REVIEW

**Comment by MichalLytek** [comment]
I still don't know how to git but now at least no merge conflict.

**Comment by blakeembrey** [comment]
@19majkel94 For the PR, can you just put the overloads directly below? You don't need to duplicate the comments 😄 

On the rebase, you can reset history back to before the change, then pull back from upstream to fix it. Not sure if there's another recommended way.

**Comment by MichalLytek** [comment]
@blakeembrey 

> For the PR, can you just put the overloads directly below? You don't need to duplicate the comments :smile:

I thought that it works but I checked and there was no intelisense comment on overloaded function. And the comments are not duplicated, the second overload don't render with locals.

**Comment by MichalLytek** [comment]
This is how it now shows in VS Code:

2016-09-13 10_03_52-startowa
2016-09-13 10_03_57-startowa

It would be better to rollback to an earlier commit or split this definitions to 4 clean overloads without "?" on params.

**Pull request merged**
