### PR TITLE
Fixed function overloading and combining Options with locals.

### PR DESCRIPTION
**Pull request by MichalLytek**

### CODE REVIEW

**Comment by MichalLytek** [comment]
I don't know why this pull request has 5 commits when I added now only 2 new commits. Should I merge this repo into my fork first?

**Comment by blakeembrey** [comment]
@19majkel94 Because you didn't rebase. You should consider branches as temporary pieces of work and delete them when you're done. I rebased your commit so the history is different to yours, resulting in a conflict.

**Comment by felixfbecker** [comment]
Also, never open a PR from your `master`. Always make a new branch for a PR, which you can then easily rebase on `master` when `master` gets updated.

**Comment by unional** [comment]
@felixfbecker why not from `master`? Forked `master` and the source `master` are just different branches. As long as I work on one PR at a time (which is most of the case for `@types` or most one-off PR you tries to contribute), I don't see an issue with PR from `master`.

I'm doing that quite frequently myself, so if there is a good reason not to do it, it will help me to acquire better practice also. 🌷

**Comment by blakeembrey** [comment]
@unional I wouldn't promote making a PR from `master` either. It's unusual to fix the remote tracking of `master` after a squash of history. Especially for someone new to Git or GitHub.

Also, it's entirely possible that while waiting for your first PR to merge, you'd want to make another. Using `master` for this just makes things awkward to manage.

**Comment by felixfbecker** [comment]
The second you want to start working on another PR or master gets updated it gets messy

**Pull request closed without merging**
